# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    cooldown:
      default-days: 7
    directories:
      - "**/*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      cosmos-security:
        applies-to: security-updates
        patterns:
          - "cosmossdk.io/*"
          - "github.com/cometbft/*"
          - "github.com/cosmos/*"
      go-security:
        applies-to: security-updates
        patterns:
          - "*"
